### ISSUE TITLE
Storage provisioner doesn't get enabled

### ISSUE THREAD

**Issue by sohaib94** [scott-the-programmer/terraform-provider-minikube#69]
Trying to run a minikube cluster and enable `storage-provisioner` addon with below block but addon doesn't get enabled

```

resource "minikube_cluster" "docker" {
  cluster_name = "minikube"

  driver              = "docker"
  auto_update_drivers = true
  container_runtime   = "docker"

  cpus   = 4
  memory = "16384mb"

  cni = "calico"

  wait = ["all"]

  addons = [
    "dashboard",
    "default-storageclass",
    "storage-provisioner",
    "ingress",
    "ingress-dns",
    "istio",
    "istio-provisioner",
    "logviewer",
    "metrics-server"
  ]
}

```

**Comment by sohaib94** [comment]
FYI in case anyone has this still, it's possible to work around this with a `local-exec` provisioner block at the end of the `minikube_cluster` resource like so:
```
provisioner "local-exec" {
    command = "minikube addons enable storage-provisioner"
  }
```

**Comment by scott-the-programmer** [comment]
Thank you for raising this! 

I think I've found the issue - it turns out there are 2 places where the addon list needs to be passed in. Namely, the [provision step](https://github.com/scott-the-programmer/terraform-provider-minikube/blob/5a5f903a57f21bffb8c25fb81821affe4ac34155/minikube/service/minikube_client.go#LL154C45-L154C45) step and when the [nodes startup](https://github.com/scott-the-programmer/terraform-provider-minikube/blob/5a5f903a57f21bffb8c25fb81821affe4ac34155/minikube/service/minikube_client.go#LL175C25-L175C25) (the former of which is missing)

This [fix](https://github.com/scott-the-programmer/terraform-provider-minikube/pull/70) seems promising, I'll try to polish it up and cut a release sometime tomorrow 

```console
minikube addons list
|-----------------------------|----------|--------------|--------------------------------|
|         ADDON NAME          | PROFILE  |    STATUS    |           MAINTAINER           |
|-----------------------------|----------|--------------|--------------------------------|
| ambassador                  | minikube | disabled     | 3rd party (Ambassador)         |
| auto-pause                  | minikube | disabled     | Google                         |
| cloud-spanner               | minikube | disabled     | Google                         |
| csi-hostpath-driver         | minikube | disabled     | Kubernetes                     |
| dashboard                   | minikube | enabled ✅   | Kubernetes                     |
| default-storageclass        | minikube | enabled ✅   | Kubernetes                     |
| efk                         | minikube | disabled     | 3rd party (Elastic)            |
| freshpod                    | minikube | disabled     | Google                         |
| gcp-auth                    | minikube | disabled     | Google                         |
| gvisor                      | minikube | disabled     | Google                         |
| headlamp                    | minikube | disabled     | 3rd party (kinvolk.io)         |
| helm-tiller                 | minikube | disabled     | 3rd party (Helm)               |
| inaccel                     | minikube | disabled     | 3rd party (InAccel             |
|                             |          |              | [info@inaccel.com])            |
| ingress                     | minikube | enabled ✅   | Kubernetes                     |
| ingress-dns                 | minikube | enabled ✅   | Google                         |
| istio                       | minikube | enabled ✅   | 3rd party (Istio)              |
| istio-provisioner           | minikube | enabled ✅   | 3rd party (Istio)              |
| kong                        | minikube | disabled     | 3rd party (Kong HQ)            |
| kubevirt                    | minikube | disabled     | 3rd party (KubeVirt)           |
| logviewer                   | minikube | enabled ✅   | 3rd party (unknown)            |
| metallb                     | minikube | disabled     | 3rd party (MetalLB)            |
| metrics-server              | minikube | enabled ✅   | Kubernetes                     |
| nvidia-driver-installer     | minikube | disabled     | Google                         |
| nvidia-gpu-device-plugin    | minikube | disabled     | 3rd party (Nvidia)             |
| olm                         | minikube | disabled     | 3rd party (Operator Framework) |
| pod-security-policy         | minikube | disabled     | 3rd party (unknown)            |
| portainer                   | minikube | disabled     | 3rd party (Portainer.io)       |
| registry                    | minikube | disabled     | Google                         |
| registry-aliases            | minikube | disabled     | 3rd party (unknown)            |
| registry-creds              | minikube | disabled     | 3rd party (UPMC Enterprises)   |
| storage-provisioner         | minikube | enabled ✅   | Google                         |
| storage-provisioner-gluster | minikube | disabled     | 3rd party (Gluster)            |
| volumesnapshots             | minikube | disabled     | Kubernetes                     |
|-----------------------------|----------|--------------|--------------------------------|
```

Thanks again!

**Comment by scott-the-programmer** [comment]
https://github.com/scott-the-programmer/terraform-provider-minikube/releases/tag/v0.2.7 should fix this issue 🎉

**Comment by sohaib94** [comment]
Amazing - thank you! Do you know when that'll update the terraform registry? It's still showing as 0.2.6 as the latest
